### ISSUE TITLE
Add a lint rule not to allow the 'require' function to load module.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#237]
To avoid confusing situation, it's better to restrict using the 'require' function. Let's add a new lint rule for it and then only use |import| instead of |require|.

**Comment by nadongguri** [comment]
Okay.

**Comment by daehyunjimmy** [comment]
when I try to find it with eslint config, it seems there is no rules for this restriction.

**Comment by nadongguri** [comment]
@daehyunjimmy is right, there's no existing rule for disallowing require, so I will create a custom rule for it.

**Comment by JayChl** [comment]
We can close this issue?

**Comment by nadongguri** [comment]
I'm closing this issue. That feature is already applied in absolute 1.0.
