### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#260]
We have many branches but most of them are unnecessary. So, we should remove them.

**Comment by romandev** [comment]
Please check the following link and then remove unnecessary branches.
https://github.com/romandev/absolute/branches/yours

**Comment by romandev** [comment]
Please check the following link and then remove unnecessary branches.
https://github.com/romandev/absolute/branches/yours

**Comment by nadongguri** [comment]
@romandev, I'm closing this issue, you can re-open it if you want. I think now is fine to remove all unnecessary without notice.
