### ISSUE TITLE
Individual role check of project members.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#263]
Authentication @romandev
Location (Physical Web + Geolocation) @gogag1
Push & SW Cache @JayChl, @daehyunjimmy 
Order API & UI @coconutperm, @cs-lee, @Wuseok 
Payments @coconutperm, @hyungheo 
DevOps @romandev, @nadongguri

**Comment by nadongguri** [comment]
Close this issue, you can re-open it if you want.
