### ISSUE TITLE
Consider introducing agile development process.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#266]
- Let's talk about the following topics.
  - Can we use scrum way?
    - If so, how long is sprint length appropriate?
    - If so, how can we do daily-meeting?
  - Can we use TDD and CI?
    - We must do it to increase quality of codes. (even if we don't use TDD strictly)
    - If so, what range is our tests?
    - We already introduced Continuous Integration via Travis.

(TBW)

**Comment by romandev** [comment]
* Introduce agile tool for github.
  - https://www.zenhub.com/
  - Restriction: it requires installing Chrome Extension.

**Comment by nadongguri** [comment]
Close this issue, you can re-open it if you want.
