### ISSUE TITLE
bootstrap/test/test-update.js implementation

### ISSUE THREAD

**Issue by Wuseok** [lunchclass/absolute#270]
We need to check 'npm upate' working or not.
Current status is 
If package.json file is modified, to check modified date of this file, start to npm update command.
after finish update, it saved update time to .pkg_timestamp file. 

We have to check 
if(timestamp > package.json modified time) true : false

**Comment by romandev** [comment]
Can you implement this test before next meeting?

**Comment by Wuseok** [comment]
Hello romandev I update pull request. 
Could you check it?

**Comment by nadongguri** [comment]
@Wuseok, I'm closing this issue.
