### ISSUE TITLE
To create Server test environment

### ISSUE THREAD

**Issue by Wuseok** [lunchclass/absolute#297]
In case of server side test, we should to start server before testing.
I will create test folder like this (/server/test/) and putting start server module before start testing.

**Comment by Wuseok** [comment]
Hello @romandev 
I checked to start server in mocha but it is not easy.
I have some issue and failed to start absolute server.

1. start command (./absolute start) using spawnSync
- I try to start server using this command but ENOENT error was comes up.
2. /server/test/ is not possible because this code < return gulp.src(['./server/**/*.js']) > this command is included gulpfile.babel.js
3. Access out/server folder and start server.js file
- If bootstrap test was succeed, out/server folder and file was created but is it OK about this flow?

**Comment by romandev** [comment]
I'll take this.

**Comment by nadongguri** [comment]
@Wuseok, I'm closing this issue.
