### ISSUE TITLE
Implement lint-fix command.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#307]
We already have |lint| command to check lint errors but it doesn't fix code actually.
So, we need to add --fix option for |lint| command and it will provide convenience to us.

**Comment by nadongguri** [comment]
As far as I know, lint rules reporting warnings and errors usually provide fix features but some are don't. I'm wondering there is a way to add fix option in user specific path not in module folder that lint-plugin is installed. :-)

**Comment by nadongguri** [comment]
Close this issue, you can re-open it if you want.
