### ISSUE TITLE
Need discussion of diagram for order schema

### ISSUE THREAD

**Issue by coconutperm** [lunchclass/absolute#312]
One order consists of a number of main menus, and one main menu consists of a number of option menus.

![main](https://user-images.githubusercontent.com/23692226/27036763-daad0f6a-4fc0-11e7-8848-2bc39d56daab.PNG)

![option](https://user-images.githubusercontent.com/23692226/27035962-3a206148-4fbe-11e7-890c-496fb32e559e.PNG)

The main menu contains mandatory options and additional options. Each option value is an id in the option table.

The coupon is created separately from the menu, and depending on the attribute of the coupon, there is menu and dependancy. And the coupon is used to calculate the total amount.

![coupon](https://user-images.githubusercontent.com/23692226/27036043-8ada648a-4fbe-11e7-8e4d-9bbb22d98131.PNG)

The structure used in the order system is briefly described as a class diagram as follows. The total amount of an order is calculated by the ICaculator interface and can be implemented according to the situation of the merchant.

![order](https://user-images.githubusercontent.com/23692226/27036166-ed36b908-4fbe-11e7-908a-1f3f06cb87c2.PNG)

And we need to provide an admin web page where we can add menu and coupon freely and easily.

****** The above is a draft version for your understanding, not an actual implementation design. ******

**Comment by nadongguri** [comment]
@coconutperm, I'm closing this issue.
