### ISSUE TITLE
Client UI

### ISSUE THREAD

**Issue by Wuseok** [lunchclass/absolute#339]
I made draft version about Client UI using Fluid.
Please check it.
Here is draft version URL
https://www.fluidui.com/editor/live/livePreview/cF9KdElzSVJUa1NKVGNiVHdOYXBkWFJrRk1JU3FoTDFJTg==

https://www.fluidui.com/editor/live/

**Comment by Wuseok** [comment]
Hello guys.

I implement Client UI first page in here temporary.
https://github.com/Wuseok/absoulte-ui

![image](https://user-images.githubusercontent.com/23691279/29483912-fcc55992-84ed-11e7-877d-2e1bb077e24a.png)

**Comment by nadongguri** [comment]
@Wuseok ,I'm closing this issue, you can re-open it if you want. :D
