### ISSUE TITLE
Order menu design  - Please review

### ISSUE THREAD

**Issue by cs-lee** [lunchclass/absolute#340]
![order_design](https://user-images.githubusercontent.com/21388202/27641504-00a56be8-5c57-11e7-9a93-cd5283b7a076.jpg)

This is order menu design. Please review it.

**Comment by coconutperm** [comment]
It's nice design for our project, but
Decorator must have super class's instance and include constructor that has parameter of super class.

And. We should consider to implement that make to new class of product.

**Comment by Wuseok** [comment]
1. Do we support coupon also? 
2. IMHO ProductOptionDeco have to support unknown cases. 
Can we support Java Generic like T type?

**Comment by nadongguri** [comment]
@cs-lee, I'm closing this issue, you can re-open it if you want. :D
