### ISSUE TITLE
Need discussion of architecture for custom schema

### ISSUE THREAD

**Issue by coconutperm** [lunchclass/absolute#352]
We have to provide a solution for defining more free Scheme in our own constraints.
So we provide the following basic product schemes and the developer can define an extended scheme if 
desired.

* Example for default product scheme
```
export default class ProductBase {
  @schemetype.mandatory name;
  @schemetype.mandatory amount;
}
```

* Example for extended product scheme what delevoper can define
```
@scheme('product')
export default class CustomProduct extends ProductBase {
  @schemetype.mandatory category;
  @schemetype.optional size;
}
```

And the @scheme annotation defined above can help define the scheme in mongoose.

```
  static scheme(tableName) {
    return function(SchemeClass) {
      // TODO: make scheme object as 'createdScheme' for mongoose using SchemeClass
      mongoose.model(tableName, createdScheme);
      // it may return scheme model class
    };
  }
```

However, Developer must use the scheme returned by mongoose.model, which causes a problem here. I would appreciate your feedback.

**Comment by nadongguri** [comment]
Close this issue, you can re-open it if you want.
