### ISSUE TITLE
push_key.js files are always tracked after starting absolute.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#357]
The two push_key.js files(c/p/push_keys.js, s/p/push_keys.js) are modified after starting absolute because creating a new key for push. It causes inconvenient.

So, what should we do? One way is that we add their names to .gitignore.

**Comment by romandev** [comment]
@JayChl, @daehyunjimmy Can you follow this issue up?

**Comment by JayChl** [comment]
Will add this to .gitignore

**Comment by JayChl** [comment]
It's better to preserve server/push/push_key.js's form to make code simply,
however .gitignore is not affect to already commited file. 
commands
$ git update-index --assume-unchanged server/push/push_key.js
$ git update-index --assume-unchanged server/push/push_key.js; 
achive this purpose. Can we add this command to script?

**Comment by JayChl** [comment]
Closing this issue #372
