### ISSUE TITLE
Stop using relative-path in import statement.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#358]
In our absolute modules, we are using relative paths in import statement to load other modules.
For example,
```
// in server/order/router/order_router.js

import * as order from '../controller/order_controller';
```

It makes using import statement difficult.
If we can use import statement as follows, it will be convenient.
```
import * as order from 'order/router/controller/order_controller';
```

**Comment by nadongguri** [comment]
Close this issue, you can re-open it if you want.
