### ISSUE TITLE
Write a document to explain our policy to become a committer and owner.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#362]
We need to discuss our policy.
I'd like to suggest the following rule basically.

- **Contributor**: No member but he/she is contributing to our project.
- **Committer**: Project Member; he/she has a write permission.
  - 20+ Non-trivial commits and nomination?
- **Owner**: One of committers. He/she has to review his/her own module/directory.
  - 20+ Non-trivial reviews and nomination?

**Comment by nadongguri** [comment]
Close this issue, you can re-open it if you want.
