### ISSUE TITLE
Introduce TypeScript for developer performance.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#371]
The [TypeScript](https://github.com/microsoft/typescript) is a language for application-scale JavaScript. It provides many things for developer convenience such as TypeSystem and access modifiers and so on. We are already using Babel transpiler to cover ECMA 6 and 7 but the standard is still lacking. So, we can consider to introduce TypeScript for developer performance and convenience.

**Comment by nadongguri** [comment]
Close this issue, you can re-open it if you want.
