### ISSUE TITLE
Only one router class should be declared per router file

### ISSUE THREAD

**Issue by JayChl** [lunchclass/absolute#381]
Lint error occur when we define more than one router class in one router.js file,

@Application.route('/api/push/')
export default class PushRouter {
...
}

@Application.route('/api/push/token')
export default class PushTokenRouter {
...
}

46:1  error  Parsing error: Only one default export allowed per module.

**Comment by romandev** [comment]
The "export default" is only allowed once per one file.
Moreover, we already agreed to define one router class per one file.
So, I think you will have to split them into two files. WDYT?

**Comment by JayChl** [comment]
Understand!
I though we could add more than one router class in same router file if someone want to do.
Close this issue
