### ISSUE TITLE
Modulelization custom command (npm package)

### ISSUE THREAD

**Issue by GarlicB** [lunchclass/absolute#394]
this issue came from [#257].  

Last week, I wrorte 'cc.js' with the ES6 and  I made this feature available in gulpfile.babel.js. But it couldn't pass test in Travis-ci. @nadongguri said,  _import {inputRL, rl} from './bootstrap/command/cc'_ blocks ending of gulp process. 

Apart from that problem, I think my code design is not neat. More specifically, tasks in gulfile.babel.js seems to manage the topics related to the server and client. So that, my 'custom command' addition is somewhat attainable in gulpfile.babel.js. 

For this reason,  There is new opinion that it should be the node module like 'gulp-undef-task-to-default'. I think the process of importing from the npm package is more cleaner and better than existing way. Furthermore, If this issue is completed, it will be good to use it for various projects.

Anyway, this is just an opinion. What I consider more important is to hear the opinions of others.
Thanks.

**Comment by GarlicB** [comment]
https://www.npmjs.com/package/github_from_cmd

**Comment by nadongguri** [comment]
@GarlicB, I'm closing this issue.
