### ISSUE TITLE
Should apply lint for client codes.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#404]
There are too many lint errors in client side codes.
To resolve this issue, we should fix all lint errors and then add ```lint_client``` task in gulpfile.babel.js.

> /Users/zino/absolute/client/app.js
>   17:1   error  Expected 'single' syntax before 'none' syntax                                       sort-imports
>   18:1   error  Imports should be sorted alphabetically                                             sort-imports
>   18:8   error  'Push' is defined but never used                                                    no-unused-vars
>   19:18  error  Member 'MandatoryOption' of the import declaration should be sorted alphabetically  sort-imports
>   29:1   error  Unexpected var, use let or const instead                                            no-var
>   30:1   error  Unexpected var, use let or const instead                                            no-var
>   31:1   error  Unexpected var, use let or const instead                                            no-var
>   32:1   error  Line 32 exceeds the maximum line length of 80                                       max-len
>   32:1   error  Unexpected var, use let or const instead                                            no-var
> 
> /Users/zino/absolute/client/service-worker-manager.js
>    2:41  error  Missing semicolon                             semi
>    4:1   error  Unexpected var, use let or const instead      no-var
>    6:1   error  Missing JSDoc comment                         require-jsdoc
>   28:54  error  Unexpected space before function parentheses  space-before-function-paren
> 
> /Users/zino/absolute/client/service-worker.js
>    3:1   error  Unexpected var, use let or const instead      no-var
>   17:52  error  Unexpected space before function parentheses  space-before-function-paren
> 
> /Users/zino/absolute/client/product/product.js
>    19:3   error  Missing JSDoc for parameter 'cost'             valid-jsdoc
>    19:3   error  Duplicate JSDoc parameter 'product'            valid-jsdoc
>    19:3   error  Expected JSDoc for 'name' but found 'product'  valid-jsdoc
>    24:14  error  Unexpected space before function parentheses   space-before-function-paren
>    32:11  error  Unexpected space before function parentheses   space-before-function-paren
>    39:11  error  Unexpected space before function parentheses   space-before-function-paren
>    48:3   error  Duplicate JSDoc parameter 'product'            valid-jsdoc
>    48:3   error  Expected JSDoc for 'product' but found 'base'  valid-jsdoc
>    48:3   error  Expected JSDoc for 'name' but found 'product'  valid-jsdoc
>    48:3   error  Missing JSDoc for parameter 'cost'             valid-jsdoc
>    54:14  error  Unexpected space before function parentheses   space-before-function-paren
>    62:11  error  Unexpected space before function parentheses   space-before-function-paren
>    69:11  error  Unexpected space before function parentheses   space-before-function-paren
>    78:3   error  Duplicate JSDoc parameter 'product'            valid-jsdoc
>    78:3   error  Expected JSDoc for 'product' but found 'base'  valid-jsdoc
>    78:3   error  Expected JSDoc for 'name' but found 'product'  valid-jsdoc
>    78:3   error  Missing JSDoc for parameter 'cost'             valid-jsdoc
>    84:14  error  Unexpected space before function parentheses   space-before-function-paren
>    91:11  error  Unexpected space before function parentheses   space-before-function-paren
>    98:11  error  Unexpected space before function parentheses   space-before-function-paren
>   107:3   error  Duplicate JSDoc parameter 'product'            valid-jsdoc
>   107:3   error  Expected JSDoc for 'product' but found 'base'  valid-jsdoc
>   107:3   error  Expected JSDoc for 'name' but found 'product'  valid-jsdoc
>   107:3   error  Missing JSDoc for parameter 'cost'             valid-jsdoc
>   113:14  error  Unexpected space before function parentheses   space-before-function-paren
>   120:11  error  Unexpected space before function parentheses   space-before-function-paren
>   127:11  error  Unexpected space before function parentheses   space-before-function-paren
> 
> /Users/zino/absolute/client/push/notification_manager.js
>   19:16  error  Missing JSDoc comment                                require-jsdoc
>   28:3   error  Missing JSDoc for parameter 'event'                  valid-jsdoc
>   39:36  error  Expected parentheses around arrow function argument  arrow-parens
>   43:22  error  Missing trailing comma                               comma-dangle
>   49:3   error  Missing JSDoc for parameter 'event'                  valid-jsdoc
>   56:3   error  Missing JSDoc for parameter 'event'                  valid-jsdoc
>   62:23  error  'clients' is not defined                             no-undef
> 
> /Users/zino/absolute/client/push/push_key.js
>   3:1    error  Line 3 exceeds the maximum line length of 80   max-len
>   3:107  error  Missing trailing comma                         comma-dangle
>   4:4    error  Missing trailing comma                         comma-dangle
>   5:2    error  Newline required at end of file but not found  eol-last
>   5:2    error  Missing semicolon                              semi
> 
> /Users/zino/absolute/client/push/push_manager.js
>   19:16  error  Missing JSDoc comment                       require-jsdoc
>   28:3   error  Missing JSDoc for parameter 'subscription'  valid-jsdoc

**Comment by romandev** [comment]
@faruk13, if you interested in this issue, could you follow this issue up?
This is very simple. But, to prevent too large patch, we can split this change into smaller patches.
If you are interested in this issue, or you have any questions, please ping me anytime :)

**Comment by romandev** [comment]
This is not agile task.

**Comment by nadongguri** [comment]
I'm closing this issue.
