### ISSUE TITLE
Server side logging module

### ISSUE THREAD

**Issue by JayChl** [lunchclass/absolute#409]
For debugging and maintenance, need to use logger for all other absolute modules
Logger needs to provide reach information and should be configurable for product
- time-stamp
- log priority
- module and function name
- log message
Seems [winston](https://github.com/winstonjs/winston) is pretty good for nodejs logging f/w

**Comment by nadongguri** [comment]
@JayChl, I'm closing this issue, you can re-open it if you want. :D
