### ISSUE TITLE
Browser Fingerprint

### ISSUE THREAD

**Issue by daehyunjimmy** [lunchclass/absolute#413]
we need Device Fingerprint to identify users without depending on cookies or db.

I am checking below ways.
1. HTML5 Canvas Fingerprinting
https://sangwook.github.io/2014/07/29/canvas-fingerprinting.html

2. Valve 
http://valve.github.io/blog/2013/07/14/anonymous-browser-fingerprinting/

3. UniqueMachine
uses differences in WebGL rendering to identify the machine
http://uniquemachine.org/

Google, Facebook and the likes of them have indeed developed their own fingerprinting systems, but they aren’t publicly available. (https://www.quora.com/Is-there-any-open-source-project-for-device-fingerprinting)

if other ways would be good, I will update that.

**Comment by daehyunjimmy** [comment]
Canvas : https://daehyunjimmy.github.io
WebGL : https://codepen.io/jon/pen/LLPKbz

**Comment by nadongguri** [comment]
Very useful information. :+1: :100:
