### ISSUE TITLE
next readme path

### ISSUE THREAD

**Issue by newklus** [lunchclass/absolute#425]
The readme.md file will be divided into the following three items.

1st. Absolute Short description
expected result: You can get a description of each feature in the linked Feature MD file.

2nd. Getting Started Absolute
expected result: Contribute MD File , system requirement, Hot to build etc

3th. usage 
expected result: A simple example is given in text.

**Comment by nadongguri** [comment]
I'm closing this issue, you can re-open it if you want. :D
