### ISSUE TITLE
Fix lint errors in server directory.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#467]
We introduced tslint in https://github.com/lunchclass/absolute/commit/430af4a7892ec3593dff8bf19858fb008953b385. But there are still many lint errors. So, we should fix the lint errors manually as per the guide message. FYI, we are using [Micrsoft TypeScript Style Guide](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines).

You can check the lint errors as follows:
```
$ ./absolute lint
```

If you feel difficult to resolve the errors, please feel free to leave some questions here.
Also, you can split this change into multiple patches.

**Comment by yjaeseok** [comment]
I will try this issue !!
but too many issue we have, I would like to do with together :)

**Comment by haeungun** [comment]
I'll take this one together :D
