### ISSUE TITLE
Add some badges in README.md.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#468]
We have already two badges. Travis and AppVeyor. But we still need some additional badges such as Slack link and License link.

So, you can just update the following links in README.md:
  - https://img.shields.io/badge/slack-online-green.svg
  - https://img.shields.io/badge/License-Apache%202.0-yellowgreen.svg

**Comment by onyoon7** [comment]
I want to take this issue : )

**Comment by nadongguri** [comment]
@onyoon7, how's it going?

**Comment by GarlicB** [comment]
Hi, I'll take this one together.
