### ISSUE TITLE
Add manifest.json in client side to support Web App Manifest.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#469]
The web app manifest provides information about an application (such as name, author, icon, and description) in a JSON text file. The purpose of the manifest is to install web applications to the homescreen of a device, providing users with quicker access and a richer experience. Web app manifests are part of a collection of web technologies called progressive web apps, which are web applications that can be installed to the homescreen of a device without needing the user to go through an app store, along with other capabilities such as  being available offline and receiving push notifications.

Please see: https://developers.google.com/web/fundamentals/web-app-manifest/?hl=ko

**Comment by elliekwon** [comment]
I'll take this issue
