### ISSUE TITLE
Implement ./absolute clean command

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#471]
If we use the command, then remove all built outputs in out/ directory.
You can add a new task in gulpfile.ts as follows and then implement it simply.
```TypeScript
gulp.task('clean', (callback) => {
  // remove out/ directory
});
```
You can see the reference here: https://github.com/gulpjs/gulp/blob/master/docs/API.md

**Comment by sapzape** [comment]
I'll take this issue

**Comment by nadongguri** [comment]
Close this issue, #487
