### ISSUE TITLE
Stop using gulp-shell in gulpfile.ts.

### ISSUE THREAD

**Issue by romandev** [lunchclass/absolute#506]
@llighter has found that now gulp do not recommend 'gulp.shell' anymore. https://github.com/lunchclass/absolute/pull/505#discussion_r147962611
So, we should stop using gulp-shell in gulpfile.ts and then remove the package in our package.json.

**Comment by romandev** [comment]
I think @llighter will be intersted in this issue :)

**Comment by llighter** [comment]
@romandev I will replace gulp-shell with child_process!
