### ISSUE TITLE
What 'view engine' is the best for absolute?

### ISSUE THREAD

**Issue by JayChl** [lunchclass/absolute#51]
There are two most popular view engine for nodejs.
jade : https://www.npmjs.com/package/jade
 - not like html, it should be convert to jade from html
ejs : http://ejs.co/
 i it can be also use html with tags

**Comment by romandev** [comment]
or full ajax page without view engine? :)

**Comment by hyungheo** [comment]
I think if we need to template engine , it might be separated from modules(both of sever and client) better

**Comment by nadongguri** [comment]
Close this issue.
